### ISSUE TITLE
Sony ERROR: Could not capture image.

### ISSUE THREAD

**Issue by WIsbrecht** [gphoto/gphoto2#133]
Hi,

so many Sony camera users have complained about sporadic freezes or resets while capturing images. My investigation suggest that it has to do with auto focus.
These might be related issues: #117 #109 #111 #80 #83
Every time one issues a capture-image (capture-image-and-download) and the camera fails to auto focus correctly gphoto2 will timeout eventually. My Sony a58 will reset automatically after that.

For example - capturing with auto focus on:

> ➜  ~ gphoto2 --capture-image-and-download --interval=1 --force-overwrite
Time-lapse mode enabled (interval: 1s).                                        
Capturing frame #1...
New file is in location /capt0000.jpg on the camera                            
Saving file as capt0000.jpg
Deleting file /capt0000.jpg on the camera
not sleeping (3 seconds behind schedule)
Capturing frame #2...
New file is in location /capt0001.jpg on the camera                            
Saving file as capt0001.jpg
Deleting file /capt0001.jpg on the camera
not sleeping (2 seconds behind schedule)
Capturing frame #3...
New file is in location /capt0002.jpg on the camera                            
Saving file as capt0002.jpg
Deleting file /capt0002.jpg on the camera
not sleeping (2 seconds behind schedule)
Capturing frame #4...
New file is in location /capt0003.jpg on the camera                            
Saving file as capt0003.jpg
Deleting file /capt0003.jpg on the camera
not sleeping (2 seconds behind schedule)
Capturing frame #5...

in this run the camera failed to auto focus after the fourth image. While gphoto is waiting for a new event one could manually trigger a new photo by pressing the trigger button of the camera. If one fails to do so in a timely fashion gphoto will time out and throw this error message and the camera will reset.

> ERROR: Could not capture image.
ERROR: Could not capture.

otherwise the timelapse will continue until the next failed attempt to auto focus or ctrl-c.

> New file is in location /capt0004.jpg on the camera                            
Saving file as capt0004.jpg
Deleting file /capt0004.jpg on the camera
not sleeping (9 seconds behind schedule)
Capturing frame #6...
New file is in location /capt0005.jpg on the camera                            
Saving file as capt0005.jpg
Deleting file /capt0005.jpg on the camera
not sleeping (2 seconds behind schedule)
Capturing frame #7...
New file is in location /capt0006.jpg on the camera                            
Saving file as capt0006.jpg
Deleting file /capt0006.jpg on the camera
not sleeping (2 seconds behind schedule)
Capturing frame #8...

Here is a debug dump:

> ➜  ~ gphoto2 --capture-image --debug --debug-logfile gphoto_debug_af_failed.txt

... 35 sec hang, camera resets at this point ...

> ERROR: Could not capture image.                                                
ERROR: Could not capture.

[gphoto_debug_af_failed.zip](https://github.com/gphoto/gphoto2/files/1957607/gphoto_debug_af_failed.zip)

**Comment by minw428** [comment]
Is there any improvement on this?

**Comment by enricopenzo** [comment]
Same here, it's being 6 months trying to figure out a solution to this

**Comment by msmeissn** [comment]
i think I fixed the problem with capture problems with out-of-focus on the weekend..

perhaps you can retest current libgphoto2 git?

**Comment by streakerau** [comment]
Hi, thanks for looking into this and sorry for the late reply.
I installed the latest development version using gphoto2 updater (hopefully that will pull the libgphoto2 git repository).
I still encounter the same problem with:
`gphoto2 --capture-image-and-download --interval=1 --force-overwrite`

The process often stops randomly returning:
`ERROR: Could not capture image.                                                
ERROR: Could not capture.`

This happened using a Sony RX100M5 

Then I tried with a Sony RX0 and it always hangs after the first picture (no repeat shots). see output below:
`
Time-lapse mode enabled (interval: 1s).
Capturing frame #1...
Downloading... |-----------                                  \  25.0%    
Downloading... |----------------------------                 |  62.5%   
Downloading... |---------------------------------------      /  87.5%    
Downloading... |---------------------------------------------| 100.0%                                                                             New file is in location /capt0000.jpg on the camera
Saving file as capt0000.jpg
Deleting file /capt0000.jpg on the camera
`

**Comment by SiuyuenChow** [comment]
hi,
Have you solved this problem? I recently had the same problem
Model: EOS 200 dii
